"""Add amenities and additional fields to Space model

Revision ID: 51bba858e76e
Revises: 021e7e70e017
Create Date: 2025-09-23 19:42:17.838011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51bba858e76e'
down_revision = '021e7e70e017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('space', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wifi', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('parking', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('air_conditioning', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('kitchen', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('workspace', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('projector', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('area_sqm', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('floor', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bathrooms', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('available_hours', sa.String(length=100), nullable=True, server_default="'24/7'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('space', schema=None) as batch_op:
        batch_op.drop_column('available_hours')
        batch_op.drop_column('bathrooms')
        batch_op.drop_column('floor')
        batch_op.drop_column('area_sqm')
        batch_op.drop_column('projector')
        batch_op.drop_column('workspace')
        batch_op.drop_column('kitchen')
        batch_op.drop_column('air_conditioning')
        batch_op.drop_column('parking')
        batch_op.drop_column('wifi')

    # ### end Alembic commands ###
